
namespace SecurePort.Entities.Models
{
    public class PermisosViewModel
    {
       
       public bool CON_CONSULTA_USU	        { get; set; }
       public bool CON_LISTA_USU            { get; set; }
       public bool CON_ALTA_USU	            { get; set; }
       public bool CON_MODIF_USU	        { get; set; }
       public bool CON_BORRA_USU	        { get; set; }
       public bool CON_MODIF_PASS_USU	    { get; set; }
       public bool CON_RESET_PASS_USU	    { get; set; }
       public bool CON_ACTIVA_USU	        { get; set; }
       public bool CON_VISUALIZAR_TODOS_USU	{ get; set; }
       public bool CON_MODIF_DEPEN_USU	    { get; set; }
       public bool CON_ADJUNTA_DOC_USU	    { get; set; }
       public bool CON_BORRA_DOC_USU	    { get; set; }
       public bool CON_MODIF_DOC_USU	    { get; set; }
       public bool CON_LISTA_PERFIL	        { get; set; }
       public bool CON_ALTA_PERFIL	        { get; set; }
       public bool CON_MODIF_PERFIL	        { get; set; }
       public bool CON_BORRA_PERFIL	        { get; set; }
       public bool CON_CONSULTA_PERFIL	    { get; set; }
       public bool CON_LISTA_GRUPO	        { get; set; }
       public bool CON_ALTA_GRUPO	        { get; set; }
       public bool CON_MODIF_GRUPO	        { get; set; }
       public bool CON_BORRA_GRUPO	        { get; set; }
       public bool CON_CONSULTA_GRUPO	    { get; set; }
       public bool CON_LISTA_ORGANISMO      { get; set; }
       public bool CON_ALTA_ORGANISMO       { get; set; }
       public bool CON_CONSULTA_ORGANISMO   { get; set; }
       public bool CON_BORRA_ORGANISMO      { get; set; }
       public bool CON_MODIF_ORGANISMO      { get; set; }
       public bool CON_ALTA_CONT_OGP        { get; set; }
       public bool CON_CONSULTA_CONT_OGP    { get; set; }
       public bool CON_BORRA_CONT_OGP       { get; set; }
       public bool CON_MODIF_CONT_OGP       { get; set; }
       public bool CON_LISTA_PAIS           { get; set; }
       public bool CON_ALTA_PAIS            { get; set; }
       public bool CON_CONSULTA_PAIS        { get; set; }
       public bool CON_BORRA_PAIS           { get; set; }
       public bool CON_MODIF_PAIS           { get; set; }
       public bool CON_ALTA_COMAUT          { get; set; }
       public bool CON_CONSULTA_COMAUT      { get; set; }
       public bool CON_BORRA_COMAUT         { get; set; }
       public bool CON_MODIF_COMAUT         { get; set; }
       public bool CON_LISTA_COMAUT         { get; set; }
       public bool CON_LISTA_Provincia      { get; set; }
       public bool CON_ALTA_Provincia       { get; set; }
       public bool CON_CONSULTA_Provincia   { get; set; }
       public bool CON_BORRA_Provincia      { get; set; }
       public bool CON_MODIF_Provincia      { get; set; }
       public bool CON_LISTA_CIUDAD         { get; set; }
       public bool CON_ALTA_CIUDAD          { get; set; }
       public bool CON_CONSULTA_CIUDAD      { get; set; }
       public bool CON_BORRA_CIUDAD         { get; set; }
       public bool CON_MODIF_CIUDAD         { get; set; }
       public bool CON_ALTA_CAPITANIA       { get; set; }
       public bool CON_CONSULTA_CAPITANIA   { get; set; }
       public bool CON_BORRA_CAPITANIA      { get; set; }
       public bool CON_MODIF_CAPITANIA      { get; set; }
       public bool CON_LISTA_CAPITANIA      { get; set; }
       public bool CON_ALTA_BIEN            { get; set; }
       public bool CON_BORRA_BIEN           { get; set; }
       public bool CON_MODIF_BIEN           { get; set; }
       public bool CON_LISTA_BIEN           { get; set; }
       public bool CON_ALTA_CENTRO          { get; set; }
       public bool CON_BORRA_CENTRO         { get; set; }
       public bool CON_MODIF_CENTRO         { get; set; }
       public bool CON_LISTA_CENTRO         { get; set; }
       public bool CON_CONSULTA_CENTRO      { get; set; }
       public bool CON_ALTA_AMENAZA         { get; set; }
       public bool CON_BORRA_AMENAZA        { get; set; }
       public bool CON_MODIF_AMENAZA        { get; set; }
       public bool CON_LISTA_AMENAZA        { get; set; }
       public bool CON_ALTA_MOTIVO          { get; set; }
       public bool CON_BORRA_MOTIVO         { get; set; }
       public bool CON_MODIF_MOTIVO         { get; set; }
       public bool CON_LISTA_MOTIVO         { get; set; }
       public bool CON_LISTA_PUERTO         { get; set; }
       public bool CON_CONSULTA_PUERTO      { get; set; }
       public bool CON_ALTA_PUERTO          { get; set; }
       public bool CON_MODIF_PUERTO         { get; set; }
       public bool CON_BORRA_PUERTO         { get; set; }
       public bool CON_LISTA_COMITE         { get; set; }
       public bool CON_CONSULTA_COMITE      { get; set; }
       public bool CON_ALTA_COMITE          { get; set; }
       public bool CON_MODIF_COMITE         { get; set; }
       public bool CON_BORRA_COMITE         { get; set; }
       public bool CON_ADJUNTA_DOC_COMITE   { get; set; }        
       public bool CON_BORRA_DOC_COMITE     { get; set; }
       public bool CON_MODIF_DOC_COMITE     { get; set; }
       public bool CON_ALTA_OPIP_IIPP       { get; set; }
       public bool CON_MODIF_OPIP_IIPP      { get; set; }
       public bool CON_BORRA_OPIP_IIPP      { get; set; }
       public bool CON_CONSULTA_OPIP_IIPP   { get; set; }
       public bool CON_ADJUNTA_DOC_IIPP     { get; set; }
       public bool CON_MODIF_DOC_IIPP       { get; set; }
       public bool CON_BORRA_DOC_IIPP       { get; set; }
       public bool CON_LISTA_FORMACION       { get; set; }
       public bool CON_ALTA_FORMACION        { get; set; }
       public bool CON_MODIF_FORMACION       { get; set; }
       public bool CON_BORRA_FORMACION       { get; set; }
       public bool CON_CONSULTA_FORMACION    { get; set; }
       public bool CON_ADJUNTA_DOC_FORMACION { get; set; }
       public bool CON_BORRA_DOC_FORMACION   { get; set; }
       public bool CON_MODIF_DOC_FORMACION   { get; set; }
       public bool CON_ALTA_OPP_PUERTO       { get; set; }
       public bool CON_MODIF_OPP_PUERTO      { get; set; }
       public bool CON_BORRA_OPP_PUERTO      { get; set; }
       public bool CON_CONSULTA_OPP_PUERTO   { get; set; }
       public bool CON_LISTA_PRACTICA        { get; set; }
       public bool CON_ALTA_PRACTICA         { get; set; }
       public bool CON_MODIF_PRACTICA        { get; set; }
       public bool CON_BORRA_PRACTICA        { get; set; }
       public bool CON_CONSULTA_PRACTICA     { get; set; }
       public bool CON_ADJUNTA_DOC_PRACTICA  { get; set; }
       public bool CON_BORRA_DOC_PRACTICA    { get; set; }
       public bool CON_MODIF_DOC_PRACTICA    { get; set; }
       public bool CON_LISTA_INCIDENTE       { get; set; }
       public bool CON_ALTA_INCIDENTE        { get; set; }
       public bool CON_MODIF_INCIDENTE       { get; set; }
       public bool CON_BORRA_INCIDENTE       { get; set; }
       public bool CON_CONSULTA_INCIDENTE    { get; set; }
       public bool CON_ADJUNTA_DOC_INCIDENTE { get; set; }
       public bool CON_BORRA_DOC_INCIDENTE   { get; set; }
       public bool CON_MODIF_DOC_INCIDENTE   { get; set; }
       public bool CON_LISTA_AUDITORIA       { get; set; }
       public bool CON_ALTA_AUDITORIA        { get; set; }
       public bool CON_MODIF_AUDITORIA       { get; set; }
       public bool CON_BORRA_AUDITORIA       { get; set; }
       public bool CON_CONSULTA_AUDITORIA    { get; set; }
       public bool CON_ADJUNTA_DOC_AUDITORIA { get; set; }
       public bool CON_BORRA_DOC_AUDITORIA   { get; set; }
       public bool CON_MODIF_DOC_AUDITORIA   { get; set; }
       public bool CON_LISTA_NIVEL           { get; set; }
       public bool CON_ALTA_NIVEL            { get; set; }
       public bool CON_MODIF_NIVEL           { get; set; }
       public bool CON_BORRA_NIVEL           { get; set; }
       public bool CON_CONSULTA_NIVEL        { get; set; }
       public bool CON_ADJUNTA_DOC_NIVEL     { get; set; }
       public bool CON_BORRA_DOC_NIVEL       { get; set; }
       public bool CON_MODIF_DOC_NIVEL       { get; set; }
       public bool CON_LISTA_MANTEN          { get; set; }
       public bool CON_ALTA_MANTEN           { get; set; }
       public bool CON_MODIF_MANTEN          { get; set; }
       public bool CON_BORRA_MANTEN          { get; set; }
       public bool CON_CONSULTA_MANTEN       { get; set; }
       public bool CON_ADJUNTA_DOC_MANTEN    { get; set; }
       public bool CON_BORRA_DOC_MANTEN      { get; set; }
       public bool CON_MODIF_DOC_MANTEN      { get; set; }
       public bool CON_LISTA_IIPP            { get; set; }
       public bool CON_ALTA_IIPP             { get; set; }
       public bool CON_CONSULTA_IIPP         { get; set; }
       public bool CON_BORRA_IIPP            { get; set; }
       public bool CON_MODIF_IIPP            { get; set; }
       public bool CON_LISTA_TIPO_IIPP       { get; set; }
       public bool CON_ALTA_TIPO_IIPP        { get; set; }
       public bool CON_BORRA_TIPO_IIPP       { get; set; }
       public bool CON_MODIF_TIPO_IIPP       { get; set; }
       public bool CON_LISTA_COMUNICA        { get; set; }
       public bool CON_ALTA_COMUNICA         { get; set; }
       public bool CON_MODIF_COMUNICA        { get; set; }
       public bool CON_BORRA_COMUNICA        { get; set; }
       public bool CON_CONSULTA_COMUNICA     { get; set; }
       public bool CON_ADJUNTA_DOC_COMUNICA  { get; set; }
       public bool CON_BORRA_DOC_COMUNICA    { get; set; }
       public bool CON_MODIF_DOC_COMUNICA    { get; set; }
       public bool CON_LISTA_DECLARA_MARIT    { get; set; }
       public bool CON_ALTA_DECLARA_MARIT     { get; set; }
       public bool CON_MODIF_DECLARA_MARIT    { get; set; }
       public bool CON_BORRA_DECLARA_MARIT    { get; set; }
       public bool CON_CONSULTA_DECLARA_MARIT { get; set; }
       public bool CON_ADJUNTA_DOC_DECLARA    { get; set; }
       public bool CON_BORRA_DOC_DECLARA      { get; set; }
       public bool CON_MODIF_DOC_DECLARA      { get; set; }
       public bool CON_LISTA_GISIS            { get; set; }
       public bool CON_ALTA_GISIS             { get; set; }
       public bool CON_MODIF_GISIS            { get; set; }
       public bool CON_BORRA_GISIS            { get; set; }
       public bool CON_CONSULTA_GISIS         { get; set; }
       public bool CON_LISTA_PLANTILLA        { get; set; }
       public bool CON_LISTA_DOCUMENTO        { get; set; }
       public bool CON_LISTA_PROCEDIM_AP            { get; set; }
       public bool CON_ALTA_PROCEDIM_AP             { get; set; }
       public bool CON_MODIF_PROCEDIM_AP            { get; set; }
       public bool CON_BORRA_PROCEDIM_AP            { get; set; }
       public bool CON_CONSULTA_PROCEDIM_AP         { get; set; }
       public bool CON_ADJUNTA_DOC_PROCEDIM_AP      { get; set; }
       public bool CON_BORRA_DOC_PROCEDIM_AP        { get; set; }
       public bool CON_MODIF_DOC_PROCEDIM_AP        { get; set; }
       public bool CON_LISTA_PROCEDIM_OPPE          { get; set; }
       public bool CON_ALTA_PROCEDIM_OPPE           { get; set; }
       public bool CON_MODIF_PROCEDIM_OPPE          { get; set; }
       public bool CON_BORRA_PROCEDIM_OPPE          { get; set; }
       public bool CON_CONSULTA_PROCEDIM_OPPE       { get; set; }
       public bool CON_ADJUNTA_DOC_PROCEDIM_OPPE    { get; set; }
       public bool CON_BORRA_DOC_PROCEDIM_OPPE      { get; set; }
       public bool CON_MODIF_DOC_PROCEDIM_OPPE      { get; set; }
       public bool CON_LISTA_PROCEDIM_OPPE_AP       { get; set; }
       public bool CON_ALTA_PROCEDIM_OPPE_AP        { get; set; }
       public bool CON_MODIF_PROCEDIM_OPPE_AP       { get; set; }
       public bool CON_BORRA_PROCEDIM_OPPE_AP       { get; set; }
       public bool CON_CONSULTA_PROCEDIM_OPPE_AP    { get; set; }
       public bool CON_ADJUNTA_DOC_PROCEDIM_OPPE_AP { get; set; }
       public bool CON_BORRA_DOC_PROCEDIM_OPPE_AP   { get; set; }
       public bool CON_MODIF_DOC_PROCEDIM_OPPE_AP   { get; set; }
       public bool EVAL_LISTA_IIPP                  { get; set; }
       public bool EVAL_GESTION_IIPP                { get; set; }
       public bool EVAL_DETALLE_IIPP                { get; set; }
       public bool EVAL_LISTA_EVAL                  { get; set; }
       public bool EVAL_ALTA_EVAL                   { get; set; }
       public bool EVAL_MODIF_EVAL                  { get; set; }
       public bool EVAL_BORRA_EVAL                  { get; set; } 
       public bool EVAL_CONSULTA_EVAL               { get; set; }
       public bool EVAL_ADJUNTA_DOC_EVAL            { get; set; }
       public bool EVAL_BORRA_DOC_EVAL              { get; set; }
       public bool EVAL_MODIF_DOC_EVAL              { get; set; }
       public bool EVAL_COMP_EVAL                   { get; set; }
       public bool EVAL_RIESGOS_EVAL                { get; set; }
        

    }
}






